---
version: "3.8"
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: job_board_db
      POSTGRES_USER: job_board_user
      POSTGRES_PASSWORD: job_board_password
    ports:
      - 5432:5432
volumes:
  postgres_data: null
