# Generated by Django 4.2.16 on 2024-10-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="is_active",
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("EXPIRED", "Expired"),
                    ("ARCHIVED", "Archived"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
