# Generated by Django 4.2.16 on 2024-10-27 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_job_is_active_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="posted_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
