# Generated by Django 4.2.16 on 2024-10-30 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_job_posted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="application_url",
            field=models.URLField(
                blank=True,
                help_text="URL for external applications",
                max_length=2000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(
                blank=True, default="Remote", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ACTIVE", "Active"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("job", "applicant")},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("stripe_session_id", models.CharField(max_length=200)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("items", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
