# Generated by Django 4.2.16 on 2024-11-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("JS", "Job Seeker"), ("EM", "Employer"), ("AD", "Admin")],
                max_length=2,
                null=True,
            ),
        ),
    ]
